### ISSUE TITLE
Release version 1.0.1

### ISSUE THREAD

**Issue by ncallister** [ascom-au/asterisk-role#4] opened 2015-04-22 06:12 UTC
Trac Ticket: [#5946](https://119.9.13.178/iwsoftware/ticket/5946)

Release version 1.0.1. 

Using [the release procedure on the trac wiki](https://119.9.13.178/iwsoftware/wiki/Processes/Release/AnsibleRoles):

  * [x] Ensure that there is an issue for the release in the release milestone in order to track any changes required
  * [x] Ensure that all issues assigned to the release milestone have been closed (except for the release issue)
  * [x] Ensure that all issues that have resulted in commits have been closed (you will need to dig through the commit messages because many of the issues will belong to playbook projects)
  * [x] Ensure that all issue specific branches have been merged and removed 
  * [x] Create a tag for the release version
  * [x] Close the release issue
  * [x] Close the milestone
  * [x] Create a milestone for the next release by creating the issue to release the next version
  * [x] ~~Create a new branch using the release version if it is a feature release~~ (N/A)

**Comment by ncallister** [comment] 2015-04-23 00:06
## Issues included in release

 * #3

**Comment by njsand** [comment] 2015-04-24 03:42
## Review ##

Ok all looks good.

1. Please close milestone above.
2. Please create new milestone.  
    Honestly I don't think we should create release tickets until it's deemed a release needs to be made.  The ideal piece of software is one that is done and never has to be modified because it was designed so beautifully it will work from now until the end of time.  According to this ideal, we may never release this software ever again - in fact we should be aiming for such a thing as we go about our daily toil.  Creating a ticket for the next release violates this ideal and thus should be viewed with suspicion.

   However, as a concession to the grubby reality of software at the current state of the art, I do not mind if a release ticket for the next version is created.  Just the milestone would be fine by me.
3. The link to the release proc in the comment above is to the old trac (1.5).  Suggest fixup.
4. While we are at doing stuff, I think we can remove the "close the release ticket" from the release procedure.  This is implied by the normal ticket system - no-one can just close a ticket and the reviewer/process we follow will make sure everything is tidied up.  (Just thinking out loud here because it means we can avoid the extra review back and forth - probably this is a very minor point that can be ignored.)

**Comment by rshamsundar** [comment] 2015-04-30 04:41
### Response
1. Closed the milestone 1.0.1
2. Created a new milestone 1.0.2 and a ticket for the next release simple because it's mentioned in the procedure
3. Fixed up TRAC link
4. Removed the "close release issue" step in the release procedure. You are right. That doesnt make sense

**Comment by njsand** [comment] 2015-05-01 00:28
Ok cool closing this ticket.

**Closed by njsand** 2015-05-01 00:28 UTC
